export const ADD_FIELD = 'ADD_FIELD';
export const GET_INITIAL_FIELDS = 'GET_INITIAL_FIELDS';
export const CHANGE_FIELD_TYPE = 'CHANGE_FIELD_TYPE';
export const ADD_SUB_INPUT = 'ADD_SUB_INPUT';
export const CHANGE_PROPERTIES = 'CHANGE_PROPERTIES';